### ISSUE TITLE
Não está rodando.

### ISSUE THREAD

**Issue by brenogalinari** [grntartaglia/simple-local-share#2]
Ao executar o comando 'npm start' é apresentada a seguinte mensagem de erro:
SO: Ubuntu 15.10

> simple-local-share@1.1.0 start /var/www/simple-local-share
> node index.js

/var/www/simple-local-share/index.js:3
const express = require('express');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 4.2.0-23-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! simple-local-share@1.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simple-local-share@1.1.0 start script 'node index.js'.
npm ERR! This is most likely a problem with the simple-local-share package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls simple-local-share
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/simple-local-share/npm-debug.log

**Comment by grntartaglia** [comment]
Parece que o problema é a versão do Node.js. Você pode tentar atualizar:

``` shell
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

Mais informações aqui: https://davidwalsh.name/upgrade-nodejs

Outra possível solução é executar com `--harmony`:

``` shell
node --harmony index.js
```

Todavia, recomendo atualizar. :)

**Comment by brenogalinari** [comment]
Funcionou (Y).
